Prueba quality gate

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -35,10 +35,10 @@ jobs:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
         run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.qualitygate.wait=true -Dsonar.projectKey=cancelaciones
-      - name: Verify SonarCloud Quality Gate
-        run: |
-          status=$(curl -X GET -u ${{ secrets.SONAR_TOKEN }}: "https://sonarcloud.io/api/qualitygates/project_status?projectKey=cancelaciones" | jq -r '.projectStatus.status')
-          if [[ "$status" != "OK" ]]; then
-            echo "Quality Gate failed, push and merge not allowed"
-            exit 1
-          fi
+      # - name: Verify SonarCloud Quality Gate
+      #   run: |
+      #     status=$(curl -X GET -u ${{ secrets.SONAR_TOKEN }}: "https://sonarcloud.io/api/qualitygates/project_status?projectKey=cancelaciones" | jq -r '.projectStatus.status')
+      #     if [[ "$status" != "OK" ]]; then
+      #       echo "Quality Gate failed, push and merge not allowed"
+      #       exit 1
+      #     fi
